### ISSUE TITLE
Dataset no longer available: helmi-dezeeuw-2000-FeH 

### ISSUE THREAD

**Issue by danlester** [vaexio/vaex-examples#1]
The notebook fails to download the ndf5 file - permission denied, as you can see if you access the link directly: 
http://vaex.astro.rug.nl/data/helmi-dezeeuw-2000-FeH.hdf5

**Comment by JovanVeljanoski** [comment]
If you install `vaex` for the first time on a machine, and run
```
import vaex
df = vaex.example()
```
The download will now work. 

Cheers, 
J.
